/* ITExpresSolutions - precios aproximados por servicio, México y Costa Rica. */
(function(){
  const FLAG_MX='<span class="itx-flag itx-flag-mx" aria-label="México" role="img"><i></i><i></i><i></i></span>';
  const FLAG_CR='<span class="itx-flag itx-flag-cr" aria-label="Costa Rica" role="img"><i></i><i></i><i></i><i></i><i></i></span>';
  const DATA={
    es:{
      title:'Precios aproximados', subtitle:'Referencia orientativa. El precio final depende del diagnóstico, alcance, piezas, licencias y traslado.', mx:FLAG_MX+'<span>México (MXN)</span>', cr:FLAG_CR+'<span>Costa Rica (CRC)</span>', note:'Los precios mostrados son aproximados y pueden variar. Piezas, licencias, dominios, hosting y servicios de terceros se cotizan por separado cuando corresponda.', close:'Cerrar', request:'Solicitar este servicio', services:{
        'Computadoras':{mx:'$500–$900 MXN',cr:'₡8,000–₡15,000',desc:'Diagnóstico, mantenimiento, optimización, instalación de sistema y solución de problemas comunes.'},
        'Virus y seguridad':{mx:'$450–$800 MXN',cr:'₡7,000–₡14,000',desc:'Limpieza de malware, revisión de seguridad, configuración y recomendaciones.'},
        'Redes e Internet':{mx:'$600–$1,000 MXN',cr:'₡10,000–₡18,000',desc:'Configuración de Wi‑Fi, router, red doméstica o pequeña oficina y solución de conectividad.'},
        'Impresoras':{mx:'$400–$750 MXN',cr:'₡7,000–₡13,000',desc:'Instalación, configuración, drivers y solución de problemas de impresión.'},
        'Celulares y dispositivos':{mx:'$350–$700 MXN',cr:'₡6,000–₡12,000',desc:'Configuración, cuentas, aplicaciones, conectividad y asistencia general.'},
        'Soporte para negocios':{mx:'$700–$1,200 MXN / hora',cr:'₡12,000–₡20,000 / hora',desc:'Soporte para equipos, usuarios, redes y operación tecnológica de pequeñas empresas.'},
        'Gestión de redes sociales':{mx:'$3,500–$8,000 MXN / mes',cr:'₡55,000–₡120,000 / mes',desc:'Gestión básica de perfiles, publicaciones y orientación. Publicidad pagada no incluida.'},
        'Páginas web':{mx:'$6,000–$18,000 MXN',cr:'₡90,000–₡250,000',desc:'Sitios informativos o de servicios para pequeños negocios. Funciones avanzadas se cotizan aparte.'},
        'Presencia digital':{mx:'$2,500–$6,000 MXN',cr:'₡40,000–₡90,000',desc:'Configuración y organización de información, perfiles empresariales, enlaces y orientación digital.'},
        'Tienda en línea':{mx:'$18,000–$40,000 MXN',cr:'₡300,000–₡650,000',desc:'E-commerce básico con catálogo y funciones esenciales. Pagos, envíos e integraciones avanzadas pueden aumentar el precio.'}
      }},
    en:{
      title:'Approximate pricing', subtitle:'Reference pricing only. Final price depends on diagnosis, scope, parts, licenses and travel.', mx:FLAG_MX+'<span>Mexico (MXN)</span>', cr:FLAG_CR+'<span>Costa Rica (CRC)</span>', note:'Prices are approximate and may vary. Parts, licenses, domains, hosting and third-party services are quoted separately when applicable.', close:'Close', request:'Request this service', services:{
        'Computadoras':{mx:'$500–$900 MXN',cr:'₡8,000–₡15,000',desc:'Diagnostics, maintenance, optimization, operating-system installation and common troubleshooting.'},
        'Virus y seguridad':{mx:'$450–$800 MXN',cr:'₡7,000–₡14,000',desc:'Malware cleanup, security review, configuration and recommendations.'},
        'Redes e Internet':{mx:'$600–$1,000 MXN',cr:'₡10,000–₡18,000',desc:'Wi‑Fi, router, home or small-office network setup and connectivity troubleshooting.'},
        'Impresoras':{mx:'$400–$750 MXN',cr:'₡7,000–₡13,000',desc:'Installation, configuration, drivers and printing troubleshooting.'},
        'Celulares y dispositivos':{mx:'$350–$700 MXN',cr:'₡6,000–₡12,000',desc:'Setup, accounts, apps, connectivity and general technical assistance.'},
        'Soporte para negocios':{mx:'$700–$1,200 MXN / hour',cr:'₡12,000–₡20,000 / hour',desc:'Support for equipment, users, networks and technology operations for small businesses.'},
        'Gestión de redes sociales':{mx:'$3,500–$8,000 MXN / month',cr:'₡55,000–₡120,000 / month',desc:'Basic profile management, posting and guidance. Paid advertising is not included.'},
        'Páginas web':{mx:'$6,000–$18,000 MXN',cr:'₡90,000–₡250,000',desc:'Informational or service websites for small businesses. Advanced features are quoted separately.'},
        'Presencia digital':{mx:'$2,500–$6,000 MXN',cr:'₡40,000–₡90,000',desc:'Business information setup, profiles, links and basic digital guidance.'},
        'Tienda en línea':{mx:'$18,000–$40,000 MXN',cr:'₡300,000–₡650,000',desc:'Basic e-commerce with catalog and essential features. Payments, shipping and advanced integrations may increase the price.'}
      }}
  };
  function currentLang(){return localStorage.getItem('itexpress-language')||'es';}
  function install(){if(document.getElementById('itxPriceStyles'))return;const s=document.createElement('style');s.id='itxPriceStyles';s.textContent=`
    .itx-price-card{cursor:pointer;transition:transform .18s ease,box-shadow .18s ease;border:1px solid #dcebf0!important}.itx-price-card:hover{transform:translateY(-3px);box-shadow:0 12px 28px rgba(6,47,82,.12)!important}.itx-price-hint{display:block;margin-top:10px;font-size:12px;font-weight:800;color:#087f8e}.itx-price-modal{position:fixed;inset:0;z-index:10050;background:rgba(3,28,48,.62);display:flex;align-items:center;justify-content:center;padding:20px}.itx-price-box{width:min(520px,100%);background:#fff;border-radius:22px;box-shadow:0 24px 70px rgba(0,0,0,.28);overflow:hidden}.itx-price-head{padding:20px 22px;background:linear-gradient(135deg,#062f52,#087f8e);color:#fff;display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.itx-price-head h3{margin:0;font-size:22px}.itx-price-close{border:0;background:rgba(255,255,255,.16);color:#fff;width:34px;height:34px;border-radius:50%;font-size:20px;cursor:pointer}.itx-price-body{padding:22px}.itx-price-sub{margin:0 0 16px;color:#526875;font-size:14px;line-height:1.5}.itx-price-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:15px 0}.itx-price-country{padding:15px;border:1px solid #dcebf0;border-radius:15px;background:#f8fcfd;display:flex;flex-direction:column;gap:8px}.itx-price-country strong{display:flex;align-items:center;gap:9px;font-size:12px;color:#58717d;margin-bottom:2px}.itx-price-country b{font-size:20px;color:#062f52}.itx-flag{display:inline-flex;width:27px;height:18px;border-radius:3px;overflow:hidden;flex:0 0 27px;box-shadow:0 1px 3px rgba(0,0,0,.22);vertical-align:middle}.itx-flag i{display:block;flex:1;height:100%}.itx-flag-mx i:nth-child(1){background:#006847}.itx-flag-mx i:nth-child(2){background:#fff;position:relative}.itx-flag-mx i:nth-child(3){background:#ce1126}.itx-flag-cr{display:grid;grid-template-rows:1fr 2fr 1fr 2fr 1fr}.itx-flag-cr i:nth-child(1),.itx-flag-cr i:nth-child(3),.itx-flag-cr i:nth-child(5){background:#002b7f}.itx-flag-cr i:nth-child(2),.itx-flag-cr i:nth-child(4){background:#fff}.itx-flag-cr i:nth-child(3){background:#ce1126}.itx-price-desc{font-size:14px;line-height:1.55;color:#405864}.itx-price-note{font-size:11px;color:#6d7f87;background:#f4f8f9;border-radius:12px;padding:11px;margin-top:14px}.itx-price-request{display:inline-flex;margin-top:16px;text-decoration:none}.itx-price-pyme-badge{font-weight:800;color:#087f8e}.itx-price-modal[hidden]{display:none}@media(max-width:600px){.itx-price-modal{padding:12px}.itx-price-grid{grid-template-columns:1fr}.itx-price-box{max-height:90vh;overflow:auto}}
  `;document.head.appendChild(s);}
  function modal(key){const lang=currentLang(),d=DATA[lang],item=d.services[key];if(!item)return;let m=document.getElementById('itxPriceModal');if(!m){m=document.createElement('div');m.id='itxPriceModal';m.className='itx-price-modal';m.hidden=true;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.itx-price-close'))m.hidden=true;});document.addEventListener('keydown',e=>{if(e.key==='Escape')m.hidden=true;});}
  m.innerHTML=`<div class="itx-price-box" role="dialog" aria-modal="true" aria-labelledby="itxPriceTitle"><div class="itx-price-head"><h3 id="itxPriceTitle">${key}</h3><button class="itx-price-close" type="button" aria-label="${d.close}">×</button></div><div class="itx-price-body"><p class="itx-price-sub">${d.subtitle}</p><div class="itx-price-grid"><div class="itx-price-country"><strong>${d.mx}</strong><b>${item.mx}</b></div><div class="itx-price-country"><strong>${d.cr}</strong><b>${item.cr}</b></div></div><p class="itx-price-desc">${item.desc}</p><div class="itx-price-note">${d.note}</div><a class="btn itx-price-request" href="#contacto" data-page="contacto">🎫 ${d.request}</a></div></div>`;m.hidden=false;const a=m.querySelector('[data-page="contacto"]');if(a)a.addEventListener('click',()=>{m.hidden=true;setTimeout(()=>{const t=document.getElementById('serviceBotToggle');if(t)t.click();},80);});}
  function makeClickable(){install();document.querySelectorAll('#servicios .service-cards .card,#pymes .card').forEach((card)=>{if(card.dataset.priceReady)return;const h=card.querySelector('h3,h2,strong');if(!h)return;let key=h.textContent.trim();const aliases={'Social media management':'Gestión de redes sociales','Websites':'Páginas web','Digital presence':'Presencia digital','Online store':'Tienda en línea'};if(!DATA.es.services[key]&&aliases[key])key=aliases[key];if(!DATA.es.services[key])return;card.dataset.priceReady='1';card.dataset.priceKey=key;const hint=document.createElement('span');hint.className='itx-price-hint';hint.textContent=currentLang()==='en'?'Click for approximate pricing':'Haz clic para ver precio aproximado';card.appendChild(hint);card.addEventListener('click',()=>modal(card.dataset.priceKey));});}
  function boot(){makeClickable();setTimeout(makeClickable,500);setTimeout(makeClickable,1500);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
  new MutationObserver(()=>makeClickable()).observe(document.body,{childList:true,subtree:true});
  window.ITXPriceModal={open:modal};
})();
