/* ITExpresSolutions - Bot de tickets sin IA
   Flujo: abrir ticket + consultar ticket + regresar/cancelar.
   Idiomas: español e inglés.
   Contacto separado: teléfono/WhatsApp + correo electrónico.
*/
(function(){
  function boot(){
    const toggle=document.getElementById('serviceBotToggle'),panel=document.getElementById('serviceBot'),close=document.getElementById('serviceBotClose'),messages=document.getElementById('serviceBotMessages'),quick=document.getElementById('serviceBotQuick'),form=document.getElementById('serviceBotInputForm'),input=document.getElementById('serviceBotInput');
    if(!toggle||!panel||!close||!messages||!quick||!form||!input)return;
    const state={step:'menu',data:{},lang:localStorage.getItem('itx_bot_lang')||'es'};
    const T={
      es:{hello:'¡Hola! 👋 Soy el asistente de servicio de ITExpresSolutions.',intro:'Puedo ayudarte a abrir un ticket o consultar uno que ya tengas.',open:'🎫 Abrir un ticket',lookup:'🔎 Consultar mi ticket',country:'Primero, ¿en qué país necesitas el servicio?',mx:'México',cr:'Costa Rica',city:'¿En qué ciudad estás?',service:'¿Qué tipo de servicio necesitas?',tech:'💻 Soporte técnico',repair:'🔧 Reparación / mantenimiento',network:'🌐 Red / Wi‑Fi',printer:'🖨️ Impresora',phone:'📱 Celular',remote:'🌎 Soporte remoto',web:'🖥️ Página web / digital',other:'Otro',equipment:'¿Qué equipo o sistema está involucrado? Por ejemplo: laptop, PC, Mac, impresora, router, celular o página web.',problem:'Cuéntame brevemente qué está pasando o qué necesitas realizar.',name:'¿Cuál es tu nombre?',phoneContact:'¿Cuál es tu teléfono o WhatsApp de contacto?',email:'¿Cuál es tu correo electrónico? Lo usaremos para enviarte la confirmación del ticket y futuras actualizaciones.',invalidEmail:'Escribe un correo electrónico válido, por ejemplo: nombre@correo.com.',priority:'¿Qué tan urgente es la solicitud?',normal:'Normal',high:'Alta',urgent:'🚨 Urgente',creating:'Creando tu ticket…',noConnection:'No se pudo conectar con el sistema de tickets. Intenta nuevamente en unos momentos.',createError:'No pude crear el ticket en este momento. Intenta nuevamente.',created:'✅ Ticket creado correctamente.',ref:'Número de referencia: #',save:'Guarda este número. Lo necesitarás para consultar el estado de tu ticket.',consult:'🔎 Consultar este ticket',newTicket:'↻ Abrir otro ticket',home:'🏠 Inicio',consulting:'Consultando tu ticket…',noFound:'No encontré un ticket con esos datos. Verifica la referencia y el teléfono, WhatsApp o correo e inténtalo nuevamente.',tryAgain:'🔎 Intentar otra vez',otherTicket:'🔎 Consultar otro ticket',askRef:'Escribe el número de referencia de tu ticket. Puedes usar los primeros 8 caracteres, por ejemplo: A1B2C3D4.',askContact:'Ahora escribe el mismo teléfono, WhatsApp o correo que registraste al abrir el ticket.',back:'← Regresar',cancel:'✖ Cancelar solicitud',cancelled:'❌ Solicitud cancelada. No se creó ningún ticket.',whatNow:'¿Qué deseas hacer ahora?',select:'Selecciona si quieres abrir un ticket o consultar uno existente.',finishing:'Estoy terminando la operación.',registered:'Tu ticket ya fue registrado. Puedes consultarlo con su número de referencia.',options:'Usa una de las opciones disponibles.',lang:'ES',robot:'Asistente robot',status:{pendiente:'🟡 Pendiente',asignado:'🔵 Asignado',en_proceso:'🟠 En proceso',completado:'🟢 Completado',cancelado:'🔴 Cancelado'}},
      en:{hello:'Hello! 👋 I am the ITExpresSolutions service assistant.',intro:'I can help you open a support ticket or check an existing one.',open:'🎫 Open a ticket',lookup:'🔎 Check my ticket',country:'First, which country do you need service in?',mx:'Mexico',cr:'Costa Rica',city:'Which city are you in?',service:'What type of service do you need?',tech:'💻 Technical support',repair:'🔧 Repair / maintenance',network:'🌐 Network / Wi‑Fi',printer:'🖨️ Printer',phone:'📱 Mobile phone',remote:'🌎 Remote support',web:'🖥️ Website / digital',other:'Other',equipment:'What equipment or system is involved? For example: laptop, PC, Mac, printer, router, mobile phone or website.',problem:'Briefly tell me what is happening or what you need.',name:'What is your name?',phoneContact:'What is your phone number or WhatsApp contact?',email:'What is your email address? We will use it to send your ticket confirmation and future updates.',invalidEmail:'Enter a valid email address, for example: name@example.com.',priority:'How urgent is this request?',normal:'Normal',high:'High',urgent:'🚨 Urgent',creating:'Creating your ticket…',noConnection:'Could not connect to the ticket system. Please try again shortly.',createError:'I could not create the ticket right now. Please try again.',created:'✅ Ticket created successfully.',ref:'Reference number: #',save:'Save this number. You will need it to check your ticket status.',consult:'🔎 Check this ticket',newTicket:'↻ Open another ticket',home:'🏠 Home',consulting:'Checking your ticket…',noFound:'I could not find a ticket with those details. Check the reference and phone, WhatsApp or email and try again.',tryAgain:'🔎 Try again',otherTicket:'🔎 Check another ticket',askRef:'Enter your ticket reference number. You can use the first 8 characters, for example: A1B2C3D4.',askContact:'Now enter the same phone, WhatsApp or email you used when opening the ticket.',back:'← Back',cancel:'✖ Cancel request',cancelled:'❌ Request cancelled. No ticket was created.',whatNow:'What would you like to do now?',select:'Choose whether you want to open a ticket or check an existing one.',finishing:'I am finishing the operation.',registered:'Your ticket has already been registered. You can check it using its reference number.',options:'Use one of the available options.',lang:'EN',robot:'Robot assistant',status:{pendiente:'🟡 Pending',asignado:'🔵 Assigned',en_proceso:'🟠 In progress',completado:'🟢 Completed',cancelado:'🔴 Cancelled'}}
    };
    const tr=k=>T[state.lang][k]??k;
    const safe=(v,max=500)=>String(v??'').trim().slice(0,max);
    const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(String(v||'').trim());
    function addMessage(text,who='bot'){const row=document.createElement('div');row.className='service-bot-message '+who;const bubble=document.createElement('div');bubble.className='service-bot-bubble';bubble.textContent=text;row.appendChild(bubble);messages.appendChild(row);messages.scrollTop=messages.scrollHeight;}
    function flagSvg(country){if(country==='México'||country==='Mexico')return '<svg viewBox="0 0 24 16" aria-hidden="true"><rect width="8" height="16" fill="#006847"/><rect x="8" width="8" height="16" fill="#fff"/><rect x="16" width="8" height="16" fill="#ce1126"/><circle cx="12" cy="8" r="2" fill="#9b7b32"/></svg>';return '<svg viewBox="0 0 24 16" aria-hidden="true"><rect width="24" height="16" fill="#002b7f"/><rect y="3" width="24" height="10" fill="#fff"/><rect y="5" width="24" height="6" fill="#ce1126"/></svg>';}
    function installLang(){if(document.getElementById('ticketBotLang'))return;const box=document.createElement('div');box.id='ticketBotLang';box.style.cssText='position:absolute;top:9px;right:50px;z-index:20;display:flex;gap:3px;background:rgba(0,0,0,.12);padding:3px;border-radius:14px;font:600 11px Arial,sans-serif;';['es','en'].forEach(x=>{const b=document.createElement('button');b.type='button';b.dataset.lang=x;b.textContent=x.toUpperCase();b.style.cssText='border:0;border-radius:11px;padding:3px 7px;cursor:pointer;background:'+(state.lang===x?'#fff':'transparent')+';color:'+(state.lang===x?'#075f73':'#fff')+';font-weight:700;';box.appendChild(b);});panel.style.position=panel.style.position||'relative';panel.appendChild(box);box.addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(!b||b.dataset.lang===state.lang)return;state.lang=b.dataset.lang;localStorage.setItem('itx_bot_lang',state.lang);start();});}
    function refreshLang(){const box=document.getElementById('ticketBotLang');if(box)[...box.children].forEach(b=>{b.style.background=b.dataset.lang===state.lang?'#fff':'transparent';b.style.color=b.dataset.lang===state.lang?'#075f73':'#fff';});}
    function setQuick(items,nav=true){quick.innerHTML='';(items||[]).forEach(item=>{const b=document.createElement('button');b.type='button';b.dataset.ticketValue=item.value;b.dataset.ticketLabel=item.label;if(item.country)b.innerHTML='<span class="ticket-flag">'+flagSvg(item.country)+'</span><span>'+item.label+'</span>';else b.textContent=item.label;quick.appendChild(b);});if(nav&&!['menu','sending','lookup_sending','done','lookup_done'].includes(state.step)){const back=document.createElement('button');back.type='button';back.dataset.ticketValue='back';back.dataset.ticketLabel=tr('back');back.textContent=tr('back');quick.appendChild(back);const cancel=document.createElement('button');cancel.type='button';cancel.dataset.ticketValue='cancel';cancel.dataset.ticketLabel=tr('cancel');cancel.textContent=tr('cancel');quick.appendChild(cancel);}}
    function ask(step,text,items){state.step=step;addMessage(text);setQuick(items,true);}
    function setRobotBrand(){const avatar=document.querySelector('.service-bot-avatar');if(avatar){avatar.textContent='🤖';avatar.setAttribute('aria-label',tr('robot'));}}
    function start(){state.step='menu';state.data={};messages.innerHTML='';setRobotBrand();installLang();refreshLang();addMessage(tr('hello'));addMessage(tr('intro'));setQuick([{label:tr('open'),value:'open'},{label:tr('lookup'),value:'lookup'}],false);}
    function startOpenTicket(){state.step='pais';state.data={};addMessage(tr('country'));setQuick([{label:tr('mx'),value:'México',country:'México'},{label:tr('cr'),value:'Costa Rica',country:'Costa Rica'}],true);}
    function nextAfterCountry(){ask('ciudad',tr('city'),[]);}
    function nextAfterCity(){ask('servicio',tr('service'),[{label:tr('tech'),value:'Soporte técnico'},{label:tr('repair'),value:'Reparación / mantenimiento'},{label:tr('network'),value:'Red / Wi‑Fi'},{label:tr('printer'),value:'Impresora'},{label:tr('phone'),value:'Celular'},{label:tr('remote'),value:'Soporte remoto'},{label:tr('web'),value:'Página web / digital'},{label:tr('other'),value:'Otro'}]);}
    function nextAfterService(){ask('equipo',tr('equipment'),[]);}function nextAfterEquipo(){ask('problema',tr('problem'),[]);}function nextAfterProblema(){ask('nombre',tr('name'),[]);}function nextAfterNombre(){ask('contacto',tr('phoneContact'),[]);}function nextAfterContacto(){ask('email',tr('email'),[]);}function nextAfterEmail(){ask('prioridad',tr('priority'),[{label:tr('normal'),value:'normal'},{label:tr('high'),value:'alta'},{label:tr('urgent'),value:'urgente'}]);}
    async function createTicket(){state.step='sending';setQuick([],false);addMessage(tr('creating'));const sb=window.ITExpresSupabase;if(!sb){addMessage(tr('noConnection'));setQuick([{label:tr('tryAgain'),value:'restart'},{label:tr('home'),value:'home'}],false);return;}const d=state.data;const {data,error}=await sb.rpc('crear_ticket_web',{p_pais:d.pais,p_ciudad:d.ciudad,p_servicio:d.servicio,p_equipo:d.equipo,p_problema:d.problema,p_nombre:d.nombre,p_contacto:d.contacto,p_email:d.email,p_prioridad:d.prioridad});if(error){console.error('crear_ticket_web:',error);addMessage(tr('createError'));setQuick([{label:tr('tryAgain'),value:'restart'},{label:tr('home'),value:'home'}],false);return;}const ticketId=String(data||'');state.data.ticketId=ticketId;const ref=ticketId.slice(0,8).toUpperCase()||'REGISTRADO';state.step='done';addMessage(tr('created'));addMessage(tr('ref')+ref);addMessage(tr('save'));setQuick([{label:tr('consult'),value:'lookup_now'},{label:tr('newTicket'),value:'restart'},{label:tr('home'),value:'home'}],false);}
    function startLookup(prefill){state.step='lookup_ref';state.data={ticketId:prefill||''};if(prefill)addMessage(tr('ref')+prefill);addMessage(tr('askRef'));setQuick([],true);}
    function askLookupContact(){ask('lookup_contact',tr('askContact'),[]);}
    async function lookupTicket(){state.step='lookup_sending';setQuick([],false);addMessage(tr('consulting'));const sb=window.ITExpresSupabase;if(!sb){addMessage(tr('noConnection'));setQuick([{label:tr('home'),value:'home'}],false);return;}const {data,error}=await sb.rpc('consultar_ticket_web',{p_referencia:state.data.referencia,p_contacto:state.data.lookupContacto});if(error){console.error('consultar_ticket_web:',error);state.step='lookup_error';addMessage(tr('noFound'));setQuick([{label:tr('tryAgain'),value:'lookup'},{label:tr('home'),value:'home'}],false);return;}const t=data||{};state.step='lookup_done';addMessage('🎫 Ticket #'+String(t.referencia||state.data.referencia).toUpperCase());addMessage((state.lang==='es'?'Estado: ':'Status: ')+(T[state.lang].status[t.estado]||t.estado||'Pendiente')+' · '+(state.lang==='es'?'Prioridad: ':'Priority: ')+String(t.prioridad||'normal'));if(t.titulo)addMessage((state.lang==='es'?'Servicio: ':'Service: ')+t.titulo.replace(/^Solicitud web - /,'')+'.');if(t.ciudad)addMessage((state.lang==='es'?'Ciudad registrada: ':'Registered city: ')+t.ciudad+'.');setQuick([{label:tr('otherTicket'),value:'lookup'},{label:tr('home'),value:'home'}],false);}
    function previousStep(){const map={ciudad:'pais',servicio:'ciudad',equipo:'servicio',problema:'equipo',nombre:'problema',contacto:'nombre',email:'contacto',prioridad:'email',lookup_contact:'lookup_ref'};const prev=map[state.step];if(!prev){start();return;}if(state.step==='ciudad')state.data.ciudad='';if(state.step==='servicio')state.data.servicio='';if(state.step==='equipo')state.data.equipo='';if(state.step==='problema')state.data.problema='';if(state.step==='nombre')state.data.nombre='';if(state.step==='contacto')state.data.contacto='';if(state.step==='email')state.data.email='';if(state.step==='prioridad')state.data.prioridad='';if(state.step==='lookup_contact')state.data.lookupContacto='';if(prev==='pais'){state.step='pais';addMessage(tr('country'));setQuick([{label:tr('mx'),value:'México',country:'México'},{label:tr('cr'),value:'Costa Rica',country:'Costa Rica'}],true);return;}if(prev==='servicio')nextAfterCity();else if(prev==='equipo')nextAfterService();else if(prev==='problema')nextAfterEquipo();else if(prev==='nombre')nextAfterProblema();else if(prev==='contacto')nextAfterNombre();else if(prev==='email')nextAfterContacto();else if(prev==='prioridad')nextAfterEmail();else if(prev==='lookup_ref')startLookup(state.data.ticketId);}
    function cancel(){state.step='menu';state.data={};addMessage(tr('cancelled'));addMessage(tr('whatNow'));setQuick([{label:tr('open'),value:'open'},{label:tr('lookup'),value:'lookup'}],false);}
    function handleChoice(value,label){if(value==='home'){start();return;}if(value==='cancel'){addMessage(label,'user');cancel();return;}if(value==='back'){addMessage(label,'user');previousStep();return;}if(value==='restart'){start();startOpenTicket();return;}if(value==='open'){addMessage(label,'user');startOpenTicket();return;}if(value==='lookup'){addMessage(label,'user');startLookup();return;}if(value==='lookup_now'){addMessage(label,'user');startLookup(state.data.ticketId.slice(0,8));return;}addMessage(label,'user');if(state.step==='pais'){state.data.pais=value;nextAfterCountry();return;}if(state.step==='servicio'){state.data.servicio=value;nextAfterService();return;}if(state.step==='prioridad'){state.data.prioridad=value;createTicket();return;}}
    function handleText(text){const value=safe(text);if(!value)return;addMessage(value,'user');if(state.step==='menu'){addMessage(tr('select'));setQuick([{label:tr('open'),value:'open'},{label:tr('lookup'),value:'lookup'}],false);return;}if(state.step==='ciudad'){state.data.ciudad=value;nextAfterCity();return;}if(state.step==='equipo'){state.data.equipo=value;nextAfterEquipo();return;}if(state.step==='problema'){state.data.problema=value;nextAfterProblema();return;}if(state.step==='nombre'){state.data.nombre=value;nextAfterNombre();return;}if(state.step==='contacto'){state.data.contacto=value;nextAfterContacto();return;}if(state.step==='email'){if(!validEmail(value)){addMessage(tr('invalidEmail'));return;}state.data.email=value.toLowerCase();nextAfterEmail();return;}if(state.step==='lookup_ref'){state.data.referencia=value.replace(/[^a-fA-F0-9-]/g,'').slice(0,36);askLookupContact();return;}if(state.step==='lookup_contact'){state.data.lookupContacto=value;lookupTicket();return;}if(state.step==='sending'||state.step==='lookup_sending'){addMessage(tr('finishing'));return;}if(state.step==='done'){addMessage(tr('registered'));return;}if(state.step==='lookup_done'||state.step==='lookup_error'){addMessage(tr('options'));return;}}
    function openBot(){panel.hidden=false;toggle.setAttribute('aria-expanded','true');if(!messages.children.length)start();setTimeout(()=>input.focus(),50);}function closeBot(){panel.hidden=true;toggle.setAttribute('aria-expanded','false');}
    setRobotBrand();installLang();toggle.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();panel.hidden?openBot():closeBot();},true);close.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();closeBot();},true);quick.addEventListener('click',e=>{const b=e.target.closest('[data-ticket-value]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();handleChoice(b.dataset.ticketValue,b.dataset.ticketLabel||b.textContent.trim());},true);form.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();const text=input.value;input.value='';handleText(text);},true);
  }
  function wait(){if(window.ITExpresSupabase)boot();else setTimeout(wait,100);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait);else wait();
})();
