import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-assignment-secret","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
const esc=(v:unknown)=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]??c));
const supabaseUrl=Deno.env.get("SUPABASE_URL")||"";
const serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")||"";
const resendKey=Deno.env.get("RESEND_API_KEY")||"";
const fromEmail=Deno.env.get("RESEND_FROM_EMAIL")||"onboarding@resend.dev";
const companyEmail="itexpressolutions@gmail.com",companyPhone="+52 998 466 1832",companyPhoneHref="+529984661832",website="https://itexpressolutions.com",portal="https://itexpressolutions.com/#portal",logoUrl="https://itexpressolutions.com/logo-badge.webp";
const headers={apikey:serviceKey,Authorization:`Bearer ${serviceKey}`,"Content-Type":"application/json"};
async function db(path:string){const r=await fetch(`${supabaseUrl}/rest/v1/${path}`,{headers});const text=await r.text();if(!r.ok)throw new Error(`DB ${r.status}`);return JSON.parse(text);}
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});
 if(req.method!=="POST")return json({error:"Method not allowed"},405);
 try{
  if(!supabaseUrl||!serviceKey||!resendKey)return json({error:"Server email configuration is incomplete"},500);
  const secret=req.headers.get("x-assignment-secret")||"";
  const cfg=await db("assignment_email_config?id=eq.1&select=secret");
  if(!cfg?.[0]?.secret||secret!==cfg[0].secret)return json({error:"Unauthorized"},401);
  const payload=await req.json(); const ticketId=String(payload?.ticket_id||"").trim();
  if(!ticketId)return json({error:"ticket_id is required"},400);
  const tickets=await db(`trabajos?id=eq.${encodeURIComponent(ticketId)}&select=id,titulo,descripcion,cliente_nombre,cliente_email,cliente_telefono,ciudad,tipo_servicio,prioridad,estado,fecha_programada,tecnico_id`);
  const t=tickets?.[0]; if(!t)return json({error:"Ticket not found"},404); if(!t.tecnico_id)return json({ok:true,skipped:true,reason:"unassigned"});
  const profiles=await db(`public_profiles?id=eq.${encodeURIComponent(t.tecnico_id)}&select=id,nombre,email,activo,rol`); const tech=profiles?.[0];
  const to=String(tech?.email||"").trim().toLowerCase(); if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(to))return json({ok:true,skipped:true,reason:"technician_email_missing"});
  const ref=String(t.id).slice(0,8).toUpperCase(), priority=String(t.prioridad||"normal"), priorityLabel=esc(priority.charAt(0).toUpperCase()+priority.slice(1)), statusValue=String(t.estado||"pendiente"), status=esc(statusValue.charAt(0).toUpperCase()+statusValue.slice(1));
  const technicianName=esc(tech?.nombre||"Técnico"), title=esc(t.titulo||t.tipo_servicio||"Soporte técnico"), description=esc(t.descripcion||"Sin descripción").replace(/\n/g,"<br>"), customer=esc(t.cliente_nombre||"No indicado"), customerEmail=esc(t.cliente_email||"No indicado"), customerPhone=esc(t.cliente_telefono||"No indicado"), city=esc(t.ciudad||"No indicada"), service=esc(t.tipo_servicio||t.titulo||"Soporte técnico");
  const scheduled=t.fecha_programada?new Date(t.fecha_programada).toLocaleString("es-MX",{dateStyle:"medium",timeStyle:"short"}):"No programado";
  const base=`font-family:Arial,Helvetica,sans-serif;background:#f4f7f9;color:#17212b;margin:0;padding:0;`;
  const header=`<div style="background:#061a2b;padding:26px 24px 22px;text-align:center;border-bottom:4px solid #63c92f;"><a href="${website}" target="_blank"><img src="${logoUrl}" alt="ITExpresSolutions" width="88" style="display:block;width:88px;height:auto;margin:0 auto 12px;border:0"></a><div style="font-size:28px;font-weight:800;color:#fff">ITExpres<span style="color:#63c92f">Solutions</span></div><div style="color:#d8e3ea;font-size:13px;margin-top:5px">Soporte • Soluciones • Tecnología</div></div>`;
  const contact=`<div style="background:#f7fafb;border:1px solid #dce6eb;border-radius:14px;padding:18px;margin-top:22px"><div style="font-size:17px;font-weight:700;color:#176f2c;margin-bottom:12px">¿Necesitas ayuda?</div><div style="font-size:14px;line-height:1.8">✉️ <strong>Correo:</strong> <a href="mailto:${companyEmail}" style="color:#176f2c;text-decoration:none">${companyEmail}</a><br>📞 <strong>Teléfono / WhatsApp:</strong> <a href="tel:${companyPhoneHref}" style="color:#176f2c;text-decoration:none">${companyPhone}</a><br>🌐 <strong>Sitio web:</strong> <a href="${website}" target="_blank" style="color:#176f2c;text-decoration:none">${website.replace("https://","")}</a></div></div>`;
  const footer=`<div style="background:#061a2b;color:#dce8ee;padding:24px;text-align:center;border-top:4px solid #63c92f"><div style="font-weight:700;font-size:15px;color:#fff">ITExpres<span style="color:#63c92f">Solutions</span></div><div style="font-size:12px;margin-top:8px">Soporte técnico profesional • Atención personalizada</div><div style="font-size:12px;margin-top:12px"><a href="mailto:${companyEmail}" style="color:#9ee36f;text-decoration:none">${companyEmail}</a>&nbsp;|&nbsp;<a href="tel:${companyPhoneHref}" style="color:#9ee36f;text-decoration:none">${companyPhone}</a></div><div style="font-size:12px;margin-top:8px"><a href="${website}" target="_blank" style="color:#9ee36f;text-decoration:none">${website}</a></div><div style="font-size:11px;color:#9aaab4;margin-top:16px">Este mensaje fue generado automáticamente por ITExpresSolutions.</div></div>`;
  const card=`<div style="background:#fff;border:1px solid #e1e8ed;border-radius:16px;padding:22px;margin-top:20px"><div style="font-size:13px;color:#647582;text-transform:uppercase;letter-spacing:.6px">Número de referencia</div><div style="font-size:25px;font-weight:800;color:#123047;margin-top:5px">#${ref}</div><hr style="border:0;border-top:1px solid #e6ecef;margin:18px 0"><div style="font-size:14px;line-height:1.9"><strong>Prioridad:</strong> ${priority==="urgente"?"🚨 ":""}${priorityLabel}<br><strong>Estado:</strong> ${status}<br><strong>Servicio:</strong> ${service}<br><strong>Ciudad:</strong> ${city}<br><strong>Programado:</strong> ${esc(scheduled)}</div></div>`;
  const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="${base}"><div style="max-width:720px;margin:0 auto;background:#fff">${header}<div style="padding:28px 24px 30px"><div style="font-size:27px;font-weight:800;color:#123047">🎫 Nuevo ticket asignado</div><p style="font-size:17px;margin-top:20px">Hola <strong>${technicianName}</strong>,</p><p style="font-size:16px;color:#536570;line-height:1.7">Se te ha asignado un nuevo ticket de soporte. Revisa los detalles en tu Panel Técnico y comienza la atención.</p>${card}<div style="margin-top:24px;font-size:18px;font-weight:800;color:#176f2c">Detalles del cliente</div><div style="background:#f7fafb;border-radius:14px;padding:18px;margin-top:10px;font-size:14px;line-height:1.9"><strong>Nombre:</strong> ${customer}<br><strong>Correo:</strong> ${customerEmail}<br><strong>Teléfono:</strong> ${customerPhone}<br><strong>Problema:</strong><br>${description}</div><div style="text-align:center;margin:26px 0"><a href="${portal}" target="_blank" style="display:inline-block;background:#45a829;color:#fff;text-decoration:none;font-weight:700;padding:14px 26px;border-radius:9px">Abrir Panel Técnico</a></div>${contact}</div>${footer}</div></body></html>`;
  const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resendKey}`,"Content-Type":"application/json"},body:JSON.stringify({from:`ITExpresSolutions <${fromEmail}>`,to:[to],subject:`${priority==="urgente"?"🚨 URGENTE — ":""}Ticket #${ref} asignado a ti | ITExpresSolutions`,html})});
  const b=await r.text(); if(!r.ok)return json({error:`Email provider HTTP ${r.status}`},502);
  return json({ok:true,sent:true,technician_email:to,reference:ref});
 }catch(err){console.error("send-assignment-email error",err);return json({error:"Unexpected error"},500)}
});
